### ISSUE TITLE
Завершение работы сразу после старта

### ISSUE THREAD

**Issue by Gatses** [Civil/github2telegram#2]
После запуска, бот сразу завершается. В логах следующее:
`{"level":"INFO","timestamp":"2018-09-20T16:29:07.420+0300","logger":"main","message":"Will apply config from file","config_file":"config.yaml"}
{"level":"DEBUG","timestamp":"2018-09-20T16:29:07.731+0300","logger":"telegram","message":"Always authorized on account","account":"bot"}
{"level":"INFO","timestamp":"2018-09-20T16:29:07.731+0300","logger":"main","message":"github2telegram initialized","config":{"Listen":":6060","Logger":[{"logger":"","file":"stdout","level":"debug","encoding":"json","encoding-time":"","encoding-duration":"","sample-tick":"","sample-initial":0,"sample-thereafter":0}],"DatabaseType":"sqlite3","DatabaseURL":"./github2telegram.db","DatabaseLogin":"","DatabasePassword":"","AdminUsername":"user","PollingInterval":300000000000,"Endpoints":{"telegram":{"Token":"token","Url":"","Type":"telegram"}}}}
{"level":"DEBUG","timestamp":"2018-09-20T16:29:07.731+0300","logger":"updateFeeds","message":"feeds initialized","feeds":null}`

**Comment by Civil** [comment]
Я немного отрефакторил код, теперь кажется работает. Возможно добавил новых багов, тут надо проверять, я пока у себя гоняю прошлую версию.
