### ISSUE TITLE
Rename repos?

### ISSUE THREAD

**Issue by Felixoid** [Civil/github2telegram#6]
Hello, there are some repos, that aren't exist anymore. For example, yandex/ClickHouse is ClickHouse/ClickHouse now. Is there any way to replace it or remove?

**Comment by Civil** [comment]
Are you talking about instance of the bot I'm running or in general?

**Comment by Civil** [comment]
If that's about my instance of the bot, could you please give me full list of repos? (or at least those that you know)

**Comment by Felixoid** [comment]
Yes, I'm telling you about @githubreleases_bot. There are known to me repos:

ClickHouse/ClickHouse:
yandex/ClickHouse: stable
yandex/ClickHouse: testing
yandex/ClickHouse: all

That's all I'm aware of.

**Comment by Civil** [comment]
Fixed
